import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <nav>
          <Link href="/">Home</Link>
          {" | "}
          <Link href="/notes">Notes</Link>
          {" | "}
          <Link href="/notes/new">Create New</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
